name: 'Terraform Deploy'

on:
  push:
    branches: [ "main" ]

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-22.04 # Фиксированная версия
    
    env:
      # Распаковываем JSON-секрет прямо в переменные, которые понимает Terraform
      ARM_CLIENT_ID: ${{ fromJSON(secrets.AZURE_CREDENTIALS).clientId }}
      ARM_CLIENT_SECRET: ${{ fromJSON(secrets.AZURE_CREDENTIALS).clientSecret }}
      ARM_SUBSCRIPTION_ID: ${{ fromJSON(secrets.AZURE_CREDENTIALS).subscriptionId }}
      ARM_TENANT_ID: ${{ fromJSON(secrets.AZURE_CREDENTIALS).tenantId }}

    defaults:
      run:
        working-directory: ./terraform

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    # --- НОВЫЙ БЛОК: ЛИНТЕР ---
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11' # Фиксированная версия Python

    - name: Install Linter
      run: pip install flake8

    - name: Run Linter
      run: flake8 app/ --count --select=E9,F63,F7,F82 --show-source --statistics
      working-directory: . # Работаем из корня, чтобы линтер видел весь код

    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: "1.7.0"

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: terraform plan

    - name: Terraform Apply
      run: terraform apply -auto-approve

    - name: Login to ACR
      run: |
        az acr login --name acrpetandrew2d5ad629
      working-directory: . # Работаем из корня

    - name: Build and Push Docker Image
      run: |
        # Собираем образ. Точка в конце означает "текущая директория" (корень)
        docker build -t acrpetandrew2d5ad629.azurecr.io/fastapi-app:${{ github.sha }} -f app/Dockerfile .
        
        # Пушим версию с хэшем
        docker push acrpetandrew2d5ad629.azurecr.io/fastapi-app:${{ github.sha }}
        
        # Тегируем как latest и пушим
        docker tag acrpetandrew2d5ad629.azurecr.io/fastapi-app:${{ github.sha }} acrpetandrew2d5ad629.azurecr.io/fastapi-app:latest
        docker push acrpetandrew2d5ad629.azurecr.io/fastapi-app:latest
      working-directory: . # Работаем из корня